# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import MPLWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 10, 241, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.openFileButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.openFileButton.setObjectName("openFileButton")
        self.verticalLayout.addWidget(self.openFileButton)
        self.graph_show_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.graph_show_button.setObjectName("graph_show_button")
        self.verticalLayout.addWidget(self.graph_show_button)
        self.graph_show_neighbors_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.graph_show_neighbors_button.setObjectName("graph_show_neighbors_button")
        self.verticalLayout.addWidget(self.graph_show_neighbors_button)
        self.dfs_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dfs_button.setObjectName("dfs_button")
        self.verticalLayout.addWidget(self.dfs_button)
        self.mplwidget = MPLWidget(self.centralwidget)
        self.mplwidget.setGeometry(QtCore.QRect(330, -1, 431, 511))
        self.mplwidget.setObjectName("mplwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openFileButton.setText(_translate("MainWindow", "打开文件"))
        self.graph_show_button.setText(_translate("MainWindow", "显示图形"))
        self.graph_show_neighbors_button.setText(_translate("MainWindow", "显示邻接点"))
        self.dfs_button.setText(_translate("MainWindow", "DFS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
