# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import MPLWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 10, 241, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.openFileButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.openFileButton.setObjectName("openFileButton")
        self.verticalLayout.addWidget(self.openFileButton)
        self.graph_show_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.graph_show_button.setObjectName("graph_show_button")
        self.verticalLayout.addWidget(self.graph_show_button)
        self.graph_show_neighbors_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.graph_show_neighbors_button.setObjectName("graph_show_neighbors_button")
        self.verticalLayout.addWidget(self.graph_show_neighbors_button)
        self.dijkstra_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dijkstra_button.setObjectName("dijkstra_button")
        self.verticalLayout.addWidget(self.dijkstra_button)
        self.dfs_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dfs_button.setObjectName("dfs_button")
        self.verticalLayout.addWidget(self.dfs_button)
        self.bfs_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bfs_button.setObjectName("bfs_button")
        self.verticalLayout.addWidget(self.bfs_button)
        self.mplwidget = MPLWidget(self.centralwidget)
        self.mplwidget.setGeometry(QtCore.QRect(330, -1, 431, 421))
        self.mplwidget.setObjectName("mplwidget")
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setGeometry(QtCore.QRect(60, 500, 691, 41))
        self.progress_bar.setAutoFillBackground(False)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progress_bar.setObjectName("progress_bar")
        self.info_board = QtWidgets.QTextEdit(self.centralwidget)
        self.info_board.setGeometry(QtCore.QRect(310, 430, 451, 71))
        self.info_board.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.info_board.setReadOnly(True)
        self.info_board.setObjectName("info_board")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openFileButton.setText(_translate("MainWindow", "打开文件"))
        self.graph_show_button.setText(_translate("MainWindow", "显示图形"))
        self.graph_show_neighbors_button.setText(_translate("MainWindow", "显示邻接点"))
        self.dijkstra_button.setText(_translate("MainWindow", "计算测地距离"))
        self.dfs_button.setText(_translate("MainWindow", "DFS"))
        self.bfs_button.setText(_translate("MainWindow", "BFS"))
        self.progress_bar.setFormat(_translate("MainWindow", "%v/%m"))
