# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from UI.mplwidget import MPLWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 600)
        MainWindow.setToolTip("")
        MainWindow.setToolTipDuration(-1)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.openFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton.setToolTipDuration(1500)
        self.openFileButton.setStyleSheet("QPushButton {\n"
                                          "    background-color: white;\n"
                                          "    border: 1px solid black;\n"
                                          "    border-radius: 10px;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: lightgray;\n"
                                          "}\n"
                                          "QPushButton:pressed {\n"
                                          "    background-color: gray;\n"
                                          "}\n"
                                          "")
        self.openFileButton.setObjectName("openFileButton")
        self.verticalLayout.addWidget(self.openFileButton)
        self.graph_show_button = QtWidgets.QPushButton(self.centralwidget)
        self.graph_show_button.setToolTipDuration(1500)
        self.graph_show_button.setStyleSheet("QPushButton {\n"
                                             "    background-color: white;\n"
                                             "    border: 1px solid black;\n"
                                             "    border-radius: 10px;\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             "    background-color: lightgray;\n"
                                             "}\n"
                                             "QPushButton:pressed {\n"
                                             "    background-color: gray;\n"
                                             "}\n"
                                             "")
        self.graph_show_button.setObjectName("graph_show_button")
        self.verticalLayout.addWidget(self.graph_show_button)
        self.graph_show_neighbors_button = QtWidgets.QPushButton(self.centralwidget)
        self.graph_show_neighbors_button.setToolTipDuration(1500)
        self.graph_show_neighbors_button.setStyleSheet("QPushButton {\n"
                                                       "    background-color: white;\n"
                                                       "    border: 1px solid black;\n"
                                                       "    border-radius: 10px;\n"
                                                       "}\n"
                                                       "QPushButton:hover {\n"
                                                       "    background-color: lightgray;\n"
                                                       "}\n"
                                                       "QPushButton:pressed {\n"
                                                       "    background-color: gray;\n"
                                                       "}\n"
                                                       "")
        self.graph_show_neighbors_button.setObjectName("graph_show_neighbors_button")
        self.verticalLayout.addWidget(self.graph_show_neighbors_button)
        self.dijkstra_button = QtWidgets.QPushButton(self.centralwidget)
        self.dijkstra_button.setToolTipDuration(1500)
        self.dijkstra_button.setStyleSheet("QPushButton {\n"
                                           "    background-color: white;\n"
                                           "    border: 1px solid black;\n"
                                           "    border-radius: 10px;\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: lightgray;\n"
                                           "}\n"
                                           "QPushButton:pressed {\n"
                                           "    background-color: gray;\n"
                                           "}\n"
                                           "")
        self.dijkstra_button.setObjectName("dijkstra_button")
        self.verticalLayout.addWidget(self.dijkstra_button)
        self.dfs_button = QtWidgets.QPushButton(self.centralwidget)
        self.dfs_button.setToolTipDuration(1500)
        self.dfs_button.setStyleSheet("QPushButton {\n"
                                      "    background-color: white;\n"
                                      "    border: 1px solid black;\n"
                                      "    border-radius: 10px;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: lightgray;\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: gray;\n"
                                      "}\n"
                                      "")
        self.dfs_button.setObjectName("dfs_button")
        self.verticalLayout.addWidget(self.dfs_button)
        self.bfs_button = QtWidgets.QPushButton(self.centralwidget)
        self.bfs_button.setToolTipDuration(1500)
        self.bfs_button.setStyleSheet("QPushButton {\n"
                                      "    background-color: white;\n"
                                      "    border: 1px solid black;\n"
                                      "    border-radius: 10px;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: lightgray;\n"
                                      "}\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: gray;\n"
                                      "}\n"
                                      "")
        self.bfs_button.setObjectName("bfs_button")
        self.verticalLayout.addWidget(self.bfs_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.mplwidget = MPLWidget(self.centralwidget)
        self.mplwidget.setObjectName("mplwidget")
        self.horizontalLayout.addWidget(self.mplwidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.info_board = QtWidgets.QTextEdit(self.centralwidget)
        self.info_board.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.info_board.setReadOnly(True)
        self.info_board.setObjectName("info_board")
        self.verticalLayout_2.addWidget(self.info_board)
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setAutoFillBackground(False)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_2.addWidget(self.progress_bar)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openFileButton.setToolTip(_translate("MainWindow", "点击以打开文件"))
        self.openFileButton.setText(_translate("MainWindow", "打开文件"))
        self.graph_show_button.setToolTip(_translate("MainWindow", "点击以显示图形"))
        self.graph_show_button.setText(_translate("MainWindow", "显示图形"))
        self.graph_show_neighbors_button.setToolTip(_translate("MainWindow", "输入一个点，显示该点的第一、第二邻接点"))
        self.graph_show_neighbors_button.setText(_translate("MainWindow", "显示邻接点"))
        self.dijkstra_button.setToolTip(_translate("MainWindow", "输入两个点，计算并显示两点的测地距离和具体路径"))
        self.dijkstra_button.setText(_translate("MainWindow", "计算测地距离"))
        self.dfs_button.setToolTip(_translate("MainWindow", "选择一个点并以深度优先绘制图形"))
        self.dfs_button.setText(_translate("MainWindow", "DFS"))
        self.bfs_button.setToolTip(_translate("MainWindow", "选择一个点并以宽度优先绘制图形"))
        self.bfs_button.setText(_translate("MainWindow", "BFS"))
        self.progress_bar.setFormat(_translate("MainWindow", "%v/%m"))
